### ISSUE TITLE
1st issue

### ISSUE THREAD

**Issue by snorfyang** [snorfyang/pandas#1]
@yusharth please help me on the branch add-typealias, you can commit directly to this branch as I have opened a draft PR.
And please note https://github.com/pandas-dev/pandas/pull/52974#issuecomment-1527002382
Before commit, please make sure ```pre-commit run --all-files``` passes on your device.

**Comment by yusharth** [comment]
@snorfyang Ok thanks for the help, I will try to do it asap.

**Comment by yusharth** [comment]
pre-commit run --all-files isn't working,
Terminal gets frozen after:
`[INFO] Locking pre-commit directory`

Also Can you please provide me with your slack would be able to ask doubts regarding the code changes etc. I am not able to found you under your username in contributing community?

**Comment by snorfyang** [comment]
> pre-commit run --all-files isn't working,
> 
> Terminal gets frozen after:
> 
> `[INFO] Locking pre-commit directory`
> 
> 
> 
> Also Can you please provide me with your slack would be able to ask doubts regarding the code changes etc. I am not able to found you under your username in contributing community?

I just joined and sent you a message, please check.
